# Generated by Django 5.2.6 on 2025-09-14 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torneio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='start_date',
        ),
    ]
