# Generated by Django 5.2.6 on 2025-09-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneio', '0002_remove_tournament_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='role',
        ),
        migrations.AlterField(
            model_name='player',
            name='character',
            field=models.CharField(help_text='Ex: Scorpion, Shunsui, Ryu', max_length=50),
        ),
    ]
