# Generated by Django 5.2.6 on 2025-09-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneio', '0003_remove_player_role_alter_player_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='tournaments', to='torneio.player'),
        ),
    ]
